export const AREA_GESTORA_CPTM = [
  { codigo: 1, descricao: '(DE.GEA.0000) GERENCIA DE MEIO AMBIENTE' },
  { codigo: 2, descricao: '(DE.GEA.DEAE.0000) DEPTO. DE MEIO AMBIENTE - EMPREENDIMENTOS' },
  { codigo: 3, descricao: '(DE.GEA.DEAO.0000) DEPTO. DE MEIO AMBIENTE - OPERAÇÃO' },
  { codigo: 5, descricao: '(DE.GEB.0000) GERENCIA DE EMPREENDIMENTOS - EXPANSÃO' },
  { codigo: 6, descricao: '(DE.GEB.DEOC.0000) DEPTO. DE OBRAS CIVIS - EXPANSÃO' },
  { codigo: 7, descricao: '(DE.GEB.DEOM.0000) DEPTO. DE MONTAGEM DE VIA PERMANENTE E RA' },
  { codigo: 8, descricao: '(DE.GEB.DEOS.0000) DEPTO. DE IMPLANTAÇÃO DE SISTEMAS - EXPANSÃO' },
  { codigo: 9, descricao: '(DE.GEC.0000) GERENCIA DE EMPREENDIMENTOS - MODERNIZAÇÃO' },
  { codigo: 10, descricao: '(DE.GEC.DEOC.0000) DEPTO. DE OBRAS CIVIS - MODERNIZAÇÃO' },
  { codigo: 11, descricao: '(DE.GEC.DEOS.0000) DEPTO. DE OBRAS DE SISTEMAS' },
  { codigo: 12, descricao: '(DE.GEC.0000) GERENCIA DE EMPREENDIMENTOS - MODERNIZAÇÃO' }, //Código duplicado na planilha
  { codigo: 14, descricao: '(DE.GER.0000) GERENCIA DE PROJETOS' },
  { codigo: 15, descricao: '(DE.GER.DEPE.0000) DEPTO. DE PROJETOS DE EDIFICAÇÕES' },
  { codigo: 16, descricao: '(DE.GER.DEPS.0000) DEPTO. DE CONSISTENCIA E INOVAÇÃO DE PROJETOS' },
  { codigo: 17, descricao: '(DE.GER.DEPI.0000) DEPTO. DE PROJETOS DE INFRAESTRUTURA' },
  { codigo: 18, descricao: '(DE.GER.DEPS.0000) DEPTO. DE PROJETOS DE INSTALAÇÕES E SISTEMAS' },
  { codigo: 19, descricao: '(DE.GET.0000) GERENCIA DE EMPREENDIMENTOS - SISTEMAS' },
  { codigo: 20, descricao: '(DE.GET.DETA.0000) DEPTO. DE SINALIZAÇÃO E TELEFONIA' },
  { codigo: 21, descricao: '(DE.GET.DETE.0000) DEPTO. DE SISTEMAS DE ENERGIA' },
  { codigo: 22, descricao: '(DE.GET.DETO.0000) DEPTO. DE PROJETOS DE IMPLANTAÇÃO DE SISTEMAS' },
  { codigo: 25, descricao: '(DE.GFA.0000) GERENCIA ADMINISTRATIVA' },
  { codigo: 29, descricao: '(DE.GFA.DFAL.0000) DEPTO. DE LOGÍSTICA ADMINISTRATIVA' },
  { codigo: 34, descricao: '(DE.GFA.DFAS.0000) DEPTO. DE SERVIÇOS ADMINISTRATIVOS' },
  { codigo: 326, descricao: '(DE.GFH.0000) GERENCIA DE DESENV. ORGAN. E RECURSOS HUMANOS' },
  { codigo: 327, descricao: '(DE.GFH.DFHS.0000) DEPTO. DE SAUDE E SEG. DO TRABALHO' },
  { codigo: 328, descricao: '(DE.GFL.0000) GERENCIA DE TECNOLOGIA DA INFORMAÇÃO' },
  { codigo: 329, descricao: '(DE.GFL.DFIM.0000) DEPTO. DE SUP. E MANUTENÇÃO DE TI' },
  { codigo: 330, descricao: '(DO.GOA.0000) GERENCIA DE ATENDIMENTO' },
  { codigo: 331, descricao: '(DO.GOA.DOAE.0000) DEPTO DE ATENDIMENTO EM ESTAÇÃO' },
  { codigo: 332, descricao: '(DO.GOA.DOAP.0000) DEPTO DE ATENDIMENTO E SEGURANÇA PATRIMONIAL' },
  { codigo: 333, descricao: '(DO.GOA.DOAS.0000) DEPTO DE ATENDIMENTO E SEGURANÇA' },
  { codigo: 49, descricao: '(DO.GOC.0000) GERENCIA CIRCULAÇÃO E CONTROLE OPERACIONAL' },
  { codigo: 334, descricao: '(DO.GOC.DOOC.0000) DEPTO. DE CIRCULAÇÃO' },
  { codigo: 66, descricao: '(DO.GOC.DOCR.0000) DEPTO. DE CONTROLE OPERACIONAL' },
  { codigo: 69, descricao: '(DO.GOC.DOCT.0000) DEPTO. DE ESTRATEGIA OPERACIONAL' },
  { codigo: 131, descricao: '(DO.GOE.0000) GERENCIA DE MANUT. DE EQUIPAMENTOS FIXOS' },
  { codigo: 132, descricao: '(DO.GOE.DOFA.0000) DEPTO. DE MANUT. DE SISTEMAS AUXILIARES' },
  { codigo: 142, descricao: '(DO.GOE.DOFE.0000) DEPTO. DE MANUT. DE SISTEMAS DE ENERGIA' },
  { codigo: 156, descricao: '(DO.GOE.DOFS.0000) DEPTO. DE MANUT. DE SISTEMAS ELETR. E RESTAB. DE SERVIÇOS' },
  { codigo: 187, descricao: '(DO.GOG.0000) GERENCIA ENG. DE OPERAÇÃO' },
  { codigo: 188, descricao: '(DO.GOG.DOGC.0000) DEPTO. ENG. DE ESTAÇÕES E COMUNICAÇÃO' },
  { codigo: 193, descricao: '(DO.GOG.DOGI.0000) DEPTO. ENG. DE SISTEMAS E EQUIPAMENTOS' },
  { codigo: 197, descricao: '(DO.GOL.0000) GERENCIA DE LOGÍSTICA' },
  { codigo: 198, descricao: '(DO.GOL.DOLA.0000) DEPTO. DE ALMOXARIFADO' },
  { codigo: 201, descricao: '(DO.GOL.DOLM.0000) DEPTO. DE GESTÃO E CADASTRO DE MATERIAIS' },
  { codigo: 38, descricao: '(DO.GOM.0000) GERENCIA GERAL DE MANUTENÇÃO' },
  { codigo: 39, descricao: '(DO.GOM.0000) GERENCIA GERAL DE OPERAÇÃO' },
  { codigo: 210, descricao: '(DO.GOR.0000) GERENCIA MANUT. MAT RODANTE E OFICINAS' },
  { codigo: 213, descricao: '(DO.GOR.DORA.0000) DEPTO. MANUT. MAT RODANTE - LAPA' },
  { codigo: 219, descricao: '(DO.GOR.DORE.0000) DEPTO. MANUT. MAT RODANTE - ENG. S. PAULO' },
  { codigo: 226, descricao: '(DO.GOR.DORO.0000) DEPTO. DE OFICINAS DE MANUT. DE EQUIPAMENTOS' },
  { codigo: 241, descricao: '(DO.GOR.DORV.0000) DEPTO. MANUT. DE VEICULOS FERROVIÁRIOS E AUXILIARES' },
  { codigo: 274, descricao: '(DO.GOT.0000) GERENCIA ENG. DE MANUTENÇÃO' },
  { codigo: 278, descricao: '(DO.GOT.DOTI.0000) DEPTO. ENG. DE MANUT. DE INSTALAÇÕES FIXAS' },
  { codigo: 281, descricao: '(DO.GOT.DOTM.0000) DEPTO. ENG. DE MANUT. DE MAT RODANTE' },
  { codigo: 286, descricao: '(DO.GOT.DOTV.0000) DEPTO. ENG. DE MANUT. DE VIA PERMANENTE E ESTRUTURA CIVIL' },
  { codigo: 289, descricao: '(DO.GOV.0000) GERENCIA DE MANUT. DE VIA PERMANENTE E ESTRUTURA CIVIL' },
  { codigo: 291, descricao: '(DO.GOV.DOVC.0000) DEPTO. DE MANUT. DE ESTRUTURA CIVIL' },
  { codigo: 297, descricao: '(DO.GOV.DOVF.0000) DEPTO. PLAN. E CONTR. DE MANUT. DE VIA PERMANENTE' },
  { codigo: 309, descricao: '(DO.GOV.DOVL.0000) DEPTO. DE MANUT. DE VIA PERMANENTE' },
  { codigo: 335, descricao: '(DR.GPM.DPMT.0000) DEPTO DE GESTÃO DO TERRITÓRIO' },
  { codigo: 336, descricao: '(DR.GPN.0000) GERENCIA DE NOVOS NEGOCIOS' },
  { codigo: 337, descricao: '(DR.GPN.DPNG.0000) DEPTO. DE GESTÃO DE NEGOCIOS' },
  { codigo: 997, descricao: 'Não se aplica(m)' },
  { codigo: 998, descricao: 'Inexistente(s)' },
  { codigo: 999, descricao: 'Indefinido(a)(s)' },
  { codigo: 1000, descricao: 'Não avaliado(a)(s)' }
];
