export const ESTACAO_CPTM = [
  { codigo: 1, descricao: 'Estação Aeroporto-Guarulhos' },
  { codigo: 2, descricao: 'Estação Água Branca' },
  { codigo: 3, descricao: 'Estação Antonio Gianetti Neto' },
  { codigo: 4, descricao: 'Estação Antônio João' },
  { codigo: 5, descricao: 'Estação Aracaré' },
  { codigo: 6, descricao: 'Estação Autódromo' },
  { codigo: 7, descricao: 'Estação Baltazar Fidélis' },
  { codigo: 8, descricao: 'Estação Barueri' },
  { codigo: 9, descricao: 'Estação Berrini' },
  { codigo: 10, descricao: 'Estação Botujuru' },
  { codigo: 11, descricao: 'Estação Brás' },
  { codigo: 12, descricao: 'Estação Braz Cubas' },
  { codigo: 13, descricao: 'Estação Caieiras' },
  { codigo: 14, descricao: 'Estação Calmon Viana' },
  { codigo: 15, descricao: 'Estação Campo Limpo Paulista' },
  { codigo: 16, descricao: 'Estação Capuava' },
  { codigo: 17, descricao: 'Estação Carapicuíba' },
  { codigo: 18, descricao: 'Estação Ceasa' },
  { codigo: 19, descricao: 'Estação Cidade Jardim' },
  { codigo: 20, descricao: 'Estação Cidade Universitária' },
  { codigo: 21, descricao: 'Estação Comandante Sampaio' },
  { codigo: 22, descricao: 'Estação Comendador Ermelino' },
  { codigo: 23, descricao: 'Estação Corinthians-Itaquera' },
  { codigo: 24, descricao: 'Estação Dom Bosco' },
  { codigo: 25, descricao: 'Estação Domingos de Moraes' },
  { codigo: 26, descricao: 'Estação Engenheiro Cardoso' },
  { codigo: 27, descricao: 'Estação Engenheiro Goulart' },
  { codigo: 28, descricao: 'Estação Engenheiro Manoel Feio' },
  { codigo: 29, descricao: 'Estação Estudantes' },
  { codigo: 30, descricao: 'Estação Ferraz de Vasconcelos' },
  { codigo: 31, descricao: 'Estação Francisco Morato' },
  { codigo: 32, descricao: 'Estação Franco da Rocha' },
  { codigo: 33, descricao: 'Estação General Miguel Costa' },
  { codigo: 34, descricao: 'Estação Grajaú' },
  { codigo: 35, descricao: 'Estação Granja Julieta' },
  { codigo: 36, descricao: 'Estação Guapituba' },
  { codigo: 37, descricao: 'Estação Guaianases' },
  { codigo: 38, descricao: 'Estação Guarulhos-Cecap' },
  { codigo: 39, descricao: 'Estação Hebraica-Rebouças' },
  { codigo: 40, descricao: 'Estação Imperatriz Leopoldina' },
  { codigo: 41, descricao: 'Estação Ipiranga' },
  { codigo: 42, descricao: 'Estação Itaim Paulista' },
  { codigo: 43, descricao: 'Estação Itapevi' },
  { codigo: 44, descricao: 'Estação Itaquaquecetuba' },
  { codigo: 45, descricao: 'Estação Jandira' },
  { codigo: 46, descricao: 'Estação Jaraguá' },
  { codigo: 47, descricao: 'Estação Jardim Belval' },
  { codigo: 48, descricao: 'Estação Jardim Helena-Vila Mara' },
  { codigo: 49, descricao: 'Estação Jardim Romano' },
  { codigo: 50, descricao: 'Estação Jardim Silveira' },
  { codigo: 51, descricao: 'Estação João Dias' },
  { codigo: 52, descricao: 'Estação José Bonifácio' },
  { codigo: 53, descricao: 'Estação Júlio Prestes' },
  { codigo: 54, descricao: 'Estação Jundiaí' },
  { codigo: 55, descricao: 'Estação Jundiapeba' },
  { codigo: 56, descricao: 'Estação Jurubatuba' },
  { codigo: 57, descricao: 'Estação Lapa (Linha 7)' },
  { codigo: 58, descricao: 'Estação Lapa (Linha 8)' },
  { codigo: 59, descricao: 'Estação Luz' },
  { codigo: 60, descricao: 'Estação Mauá' },
  { codigo: 61, descricao: 'Estação Mendes-Vila Natal' },
  { codigo: 62, descricao: 'Estação Mogi das Cruzes' },
  { codigo: 63, descricao: 'Estação Mooca' },
  { codigo: 64, descricao: 'Estação Morumbi' },
  { codigo: 65, descricao: 'Estação Osasco' },
  { codigo: 66, descricao: 'Estação Palmeiras-Barra Funda' },
  { codigo: 67, descricao: 'Estação Parada Alvarenga-Suzano' },
  { codigo: 68, descricao: 'Estação Perus' },
  { codigo: 69, descricao: 'Estação Pinheiros' },
  { codigo: 70, descricao: 'Estação Pirituba' },
  { codigo: 71, descricao: 'Estação Poá' },
  { codigo: 72, descricao: 'Estação Primavera-Interlagos' },
  { codigo: 73, descricao: 'Estação Prefeito Celso Daniel-Santo André' },
  { codigo: 74, descricao: 'Estação Prefeito Saladino' },
  { codigo: 75, descricao: 'Estação Presidente Altino' },
  { codigo: 76, descricao: 'Estação Quitaúna' },
  { codigo: 77, descricao: 'Estação Ribeirão Pires' },
  { codigo: 78, descricao: 'Estação Rio Grande da Serra' },
  { codigo: 79, descricao: 'Estação Sagrado Coração' },
  { codigo: 80, descricao: 'Estação Santa Rita' },
  { codigo: 81, descricao: 'Estação Santa Terezinha' },
  { codigo: 82, descricao: 'Estação Santo Amaro' },
  { codigo: 83, descricao: 'Estação Santo André' },
  { codigo: 84, descricao: 'Estação São Caetano' },
  { codigo: 85, descricao: 'Estação São Miguel Paulista' },
  { codigo: 86, descricao: 'Estação Socorro' },
  { codigo: 87, descricao: 'Estação Suzano' },
  { codigo: 88, descricao: 'Estação Tamanduateí' },
  { codigo: 89, descricao: 'Estação Tatuapé' },
  { codigo: 90, descricao: 'Estação USP Leste' },
  { codigo: 91, descricao: 'Estação Utinga' },
  { codigo: 92, descricao: 'Estação Várzea Paulista' },
  { codigo: 93, descricao: 'Estação Vila Aurora' },
  { codigo: 94, descricao: 'Estação Vila Clarice' },
  { codigo: 95, descricao: 'Estação Vila Olímpia' },
  { codigo: 96, descricao: 'Estação Varginha' },
  { codigo: 997, descricao: 'Não se aplica(m)' },
  { codigo: 998, descricao: 'Inexistente(s)' },
  { codigo: 999, descricao: 'Indefinido(a)(s)' },
  { codigo: 1000, descricao: 'Não avaliado(a)(s)' }
];