export const LINHA_CPTM = [
  { codigo: 1, descricao: 'Linha 07 - Rubi' },
  { codigo: 2, descricao: 'Linha 08 - Diamante' },
  { codigo: 3, descricao: 'Linha 09 - Esmeralda' },
  { codigo: 4, descricao: 'Linha 10 - Turquesa' },
  { codigo: 5, descricao: 'Linha 11 - Coral' },
  { codigo: 6, descricao: 'Linha 12 - Safira' },
  { codigo: 7, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante' },
  { codigo: 9, descricao: 'Linha 09 - Esmeralda / Linha 10 - Turquesa' },
  { codigo: 8, descricao: 'Linha 08 - Diamante / Linha 09 - Esmeralda' },
  { codigo: 10, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante / Linha 11 - Coral' },
  { codigo: 11, descricao: 'Linha 07 - Rubi / Linha 11 - Coral' },
  { codigo: 12, descricao: 'Linha 10 - Turquesa / Linha 11 - Coral' },
  { codigo: 13, descricao: 'Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 14, descricao: 'Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 15, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante / Linha 09 - Esmeralda / Linha 10 - Turquesa / Linha 11 - Coral' },
  { codigo: 16, descricao: 'Linha 08 - Diamante / Linha 09 - Esmeralda / Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 17, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante / Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 18, descricao: 'Sem linha associada' },
  { codigo: 19, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante / Linha 09 - Esmeralda / Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 20, descricao: 'Linha 13 - Jade' },
  { codigo: 21, descricao: 'Linha 05 - Lilás' },
  { codigo: 22, descricao: 'Linha 11 - Coral / Linha 12 - Safira / 13 - Jade' },
  { codigo: 23, descricao: 'Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira / Linha 13 - Jade' },
  { codigo: 24, descricao: 'Linha 07 - Rubi / Linha 10 - Turquesa' },
  { codigo: 25, descricao: 'Linha JJ - Baixada Santista' },
  { codigo: 26, descricao: 'Linha 09 - Esmeralda / Linha 05 - Lilás' },
  { codigo: 27, descricao: 'Linha 07 - Rubi / Linha 08 - Diamante / Linha 09 - Esmeralda / Linha 12 - Safira' },
  { codigo: 28, descricao: 'Linha 07 - Rubi / Linha 12 - Safira' },
  { codigo: 29, descricao: 'Linha 07 - Rubi / Linha 09 - Esmeralda' },
  { codigo: 30, descricao: 'Linha 08 - Diamante / Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira' },
  { codigo: 31, descricao: 'Linha 08 - Diamante / Linha 09 - Esmeralda / Linha 10 - Turquesa / Linha 11 - Coral / Linha 12 - Safira / Linha JJ - Baixada Santista' },
  { codigo: 32, descricao: 'Linha não informada' },
  { codigo: 33, descricao: 'Linha 12 - Safira / Linha 13 - Jade' },
  { codigo: 97, descricao: 'Não se aplica(m)' },
  { codigo: 98, descricao: 'Inexistente(s)' },
  { codigo: 99, descricao: 'Indefinido(a)(s)' },
  { codigo: 100, descricao: 'Não avaliado(a)(s)' }
];
