export const MUNICIPIO = [
  { codigo: 24, descricao: 'Arujá' },
  { codigo: 10, descricao: 'Barueri' },
  { codigo: 25, descricao: 'Biritiba-Mirim' },
  { codigo: 6,  descricao: 'Caieiras' },
  { codigo: 26, descricao: 'Cajamar' },
  { codigo: 4,  descricao: 'Campo Limpo Paulista' },
  { codigo: 11, descricao: 'Carapicuíba' },
  { codigo: 27, descricao: 'Cotia' },
  { codigo: 28, descricao: 'Diadema' },
  { codigo: 29, descricao: 'Embú' },
  { codigo: 30, descricao: 'Embú-Guaçu' },
  { codigo: 20, descricao: 'Ferraz de Vasconcelos' },
  { codigo: 5,  descricao: 'Francisco Morato' },
  { codigo: 7,  descricao: 'Franco da Rocha' },
  { codigo: 31, descricao: 'Guararema' },
  { codigo: 23, descricao: 'Guarulhos' },
  { codigo: 32, descricao: 'Itapecerica da Serra' },
  { codigo: 8,  descricao: 'Itapevi' },
  { codigo: 21, descricao: 'Itaquaquecetuba' },
  { codigo: 9,  descricao: 'Jandira' },
  { codigo: 2,  descricao: 'Jundiaí' },
  { codigo: 33, descricao: 'Juquitiba' },
  { codigo: 46, descricao: 'Mairinque' },
  { codigo: 34, descricao: 'Mairiporã' },
  { codigo: 16, descricao: 'Mauá' },
  { codigo: 18, descricao: 'Mogi das Cruzes' },
  { codigo: 12, descricao: 'Osasco' },
  { codigo: 35, descricao: 'Pirapora do Bom Jesus' },
  { codigo: 22, descricao: 'Poá' },
  { codigo: 14, descricao: 'Ribeirão Pires' },
  { codigo: 13, descricao: 'Rio Grande da Serra' },
  { codigo: 36, descricao: 'Salesópolis' },
  { codigo: 37, descricao: 'Santa Isabel' },
  { codigo: 38, descricao: 'Santana de Parnaíba' },
  { codigo: 15, descricao: 'Santo André' },
  { codigo: 45, descricao: 'Santos' },
  { codigo: 39, descricao: 'São Bernardo do Campo' },
  { codigo: 17, descricao: 'São Caetano do Sul' },
  { codigo: 40, descricao: 'São Lourenço da Serra' },
  { codigo: 1,  descricao: 'São Paulo' },
  { codigo: 43, descricao: 'São Roque' },
  { codigo: 44, descricao: 'São Vicente' },
  { codigo: 19, descricao: 'Suzano' },
  { codigo: 41, descricao: 'Taboão da Serra' },
  { codigo: 42, descricao: 'Vargem Grande Paulista' },
  { codigo: 3,  descricao: 'Várzea Paulista' },
  { codigo: 99, descricao: 'Diversos (Ver Observação)' },
  { codigo: 997, descricao: 'Não se aplica(m)' },
  { codigo: 998, descricao: 'Inexistente(s)' },
  { codigo: 999, descricao: 'Indefinido(a)(s)' },
  { codigo: 1000, descricao: 'Não avaliado(a)(s)' }
];
