export const NATUREZA_PGA = [
  { codigo: 13, descricao: 'Áreas Ambientalmente Protegidas' },
  { codigo: 3, descricao: 'Áreas Contaminadas' },
  { codigo: 1, descricao: 'Arqueologia' },
  { codigo: 18, descricao: 'Comunicação Social' },
  { codigo: 17, descricao: 'Documentação' },
  { codigo: 5, descricao: 'Efluente' },
  { codigo: 4, descricao: 'Emissões Atmosféricas' },
  { codigo: 8, descricao: 'Erosões e Movimentos de Massa' },
  { codigo: 11, descricao: 'Fauna' },
  { codigo: 10, descricao: 'Gerenciamento de Solo' },
  { codigo: 16, descricao: 'Lançamentos Irregulares' },
  { codigo: 2, descricao: 'Patrimônio Histórico' },
  { codigo: 6, descricao: 'Produtos Perigosos' },
  { codigo: 15, descricao: 'Recursos Hídricos' },
  { codigo: 7, descricao: 'Resíduos Sólidos' },
  { codigo: 14, descricao: 'Ruído e Vibração' },
  { codigo: 20, descricao: 'Segmentação Urbana' },
  { codigo: 19, descricao: 'Sinalização e Isolamento' },
  { codigo: 9, descricao: 'Sistema de Drenagem, Inundações e Alagamentos' },
  { codigo: 12, descricao: 'Vegetação' },
  { codigo: 97, descricao: 'Não se aplica(m)' },
  { codigo: 98, descricao: 'Inexistente(s)' },
  { codigo: 99, descricao: 'Indefinido(a)(s)' },
  { codigo: 100, descricao: 'Não avaliado(a)(s)' }
];
