export const TIPO_PROPRIETARIO_L13 = [
  { codigo: 1, descricao: 'CPTM - Titularidade' },
  { codigo: 2, descricao: 'CPTM - Posse' },
  { codigo: 3, descricao: 'Metrô' },
  { codigo: 4, descricao: 'Alienado' },
  { codigo: 5, descricao: 'MRS' },
  { codigo: 6, descricao: 'RFSA' },
  { codigo: 7, descricao: 'RFSA/SPU' },
  { codigo: 8, descricao: 'CBTU' },
  { codigo: 9, descricao: 'Pessoa Jurídica' },
  { codigo: 10, descricao: 'Pessoa Física' },
  { codigo: 11, descricao: 'Indefinido' },
  { codigo: 13, descricao: 'FEPASA' },
  { codigo: 14, descricao: 'Permuta' },
  { codigo: 15, descricao: 'Prefeitura de Guarulhos' },
  { codigo: 16, descricao: 'DAEE' },
  { codigo: 18, descricao: 'USP Leste' },
  { codigo: 19, descricao: 'GRU - Aeroporto' },
  { codigo: 20, descricao: 'CCR - Rodovia Dutra' },
  { codigo: 21, descricao: 'Ecopistas' },
  { codigo: 22, descricao: 'CDHU' },
  { codigo: 97, descricao: 'Não se aplica(m)' },
  { codigo: 98, descricao: 'Inexistente(s)' },
  { codigo: 100, descricao: 'Não avaliado(a)(s)' }
];