export const TRECHO_E_SENTIDO_CPTM = [
  { codigo: 124, descricao: 'Estação Aeroporto-Guarulhos > Estação Guarulhos-Cecap' },
  { codigo: 104, descricao: 'Estação Água Branca > Estação Palmeiras - Barra Funda' },
  { codigo: 25, descricao: 'Estação Água Branca > Estação Lapa' },
  { codigo: 41, descricao: 'Estação Água Branca > Estação Luz (L7)' },
  { codigo: 111, descricao: 'Estação Água Branca > Estação Palmeiras - Barra Funda' },
  { codigo: 20, descricao: 'Estação Antonio Gianetti Neto > Estação Ferraz de Vasconcelos' },
  { codigo: 45, descricao: 'Estação Antonio Gianetti Neto > Estação Guaianases' },
  { codigo: 110, descricao: 'Estação Aracaré > Estação Itaquaquecetuba' },
  { codigo: 63, descricao: 'Estação Aracaré > Estação Manoel Feio' },
  { codigo: 88, descricao: 'Estação Autódromo > Estação Interlagos' },
  { codigo: 57, descricao: 'Estação Baltazar Fidélis > Estação Francisco Morato' },
  { codigo: 23, descricao: 'Estação Baltazar Fidélis > Estação Franco da Rocha' },
  { codigo: 237, descricao: 'Estação Baltazar Fidélis > Estação Francisco Morato' },
  { codigo: 51, descricao: 'Estação Barueri > Estação Antônio João' },
  { codigo: 21, descricao: 'Estação Barueri > Estação Jardim Belval' },
  { codigo: 117, descricao: 'Estação Berrini > Estação Morumbi' },
  { codigo: 33, descricao: 'Estação Berrini > Estação Vila Olímpia' },
  { codigo: 1, descricao: 'Estação Brás > Estação Prefeito Saladino' },
  { codigo: 12, descricao: 'Estação Caieiras > Estação Baltazar Fidélis' },
  { codigo: 11, descricao: 'Estação Caieiras > Estação Perus' },
  { codigo: 73, descricao: 'Estação Calmon Viana > Estação Aracaré' },
  { codigo: 31, descricao: 'Estação Calmon Viana > Estação Poá' },
  { codigo: 40, descricao: 'Estação Calmon Viana > Estação Suzano' },
  { codigo: 114, descricao: 'Estação Calmon Viana > Estação Suzano' },
  { codigo: 50, descricao: 'Estação Campo Limpo Paulista > Estação Várzea Paulista' },
  { codigo: 3, descricao: 'Estação Carapicuíba > Estação Osasco' },
  { codigo: 2, descricao: 'Estação Carapicuíba > Estação Santa Terezinha' },
  { codigo: 3, descricao: 'Estação Comandante Sampaio > Estação Osasco' },
  { codigo: 52, descricao: 'Estação Comandante Sampaio > Estação Quitaúna' },
  { codigo: 120, descricao: 'Estação Corinthians-Itaquera > Estação Dom Bosco' },
  { codigo: 61, descricao: 'Estação Corinthians-Itaquera > Estação Guaianases' },
  { codigo: 120, descricao: 'Estação Dom Bosco > Estação Corinthians-Itaquera' },
  { codigo: 60, descricao: 'Estação Dom Bosco > Estação José Bonifácio' },
  { codigo: 122, descricao: 'Estação Engenheiro Goulart > Estação São Miguel Paulista' },
  { codigo: 118, descricao: 'Estação Engenheiro Goulart > Estação USP Leste' },
  { codigo: 110, descricao: 'Estação Engenheiro Manoel Feio > Estação Itaquaquecetuba' },
  { codigo: 112, descricao: 'Estação Engenheiro Manoel Feio > Estação Jardim Romano' },
  { codigo: 22, descricao: 'Estação Estudantes > Estação Mogi das Cruzes' },
  { codigo: 20, descricao: 'Estação Ferraz de Vasconcelos > Estação Antonio Gianetti Neto' },
  { codigo: 62, descricao: 'Estação Ferraz de Vasconcelos > Estação Poá' },
  { codigo: 12, descricao: 'Estação Francisco Morato > Estação Baltazar Fidélis' },
  { codigo: 13, descricao: 'Estação Francisco Morato > Estação Botujuru' },
  { codigo: 48, descricao: 'Estação Franco da Rocha > Estação Baltazar Fidélis' },
  { codigo: 11, descricao: 'Estação Franco da Rocha > Estação Caieiras' },
  { codigo: 45, descricao: 'Estação Guaianases > Estação Antonio Gianetti Neto' },
  { codigo: 61, descricao: 'Estação Guaianases > Estação Corinthians-Itaquera' },
  { codigo: 124, descricao: 'Estação Guarulhos-Cecap > Estação Aeroporto-Guarulhos' },
  { codigo: 123, descricao: 'Estação Guarulhos-Cecap > Estação Engenheiro Goulart' },
  { codigo: 88, descricao: 'Estação Interlagos > Estação Autódromo' },
  { codigo: 89, descricao: 'Estação Interlagos > Estação Grajaú' },
  { codigo: 115, descricao: 'Estação Itaim Paulista > Estação Jardim Helena-Vila Mara' },
  { codigo: 114, descricao: 'Estação Itaim Paulista > Estação Jardim Romano' },
  { codigo: 23, descricao: 'Estação Itapevi > Estação Engenheiro Cardoso' },
  { codigo: 24, descricao: 'Estação Itapevi > Estação Santa Rita' },
  { codigo: 110, descricao: 'Estação Itaquaquecetuba > Estação Aracaré' },
  { codigo: 111, descricao: 'Estação Itaquaquecetuba > Estação Manoel Feio' },
  { codigo: 21, descricao: 'Estação Jardim Belval > Estação Barueri' },
  { codigo: 22, descricao: 'Estação Jardim Belval > Estação Jardim Silveira' },
  { codigo: 115, descricao: 'Estação Jardim Helena-Vila Mara > Estação Itaim Paulista' },
  { codigo: 113, descricao: 'Estação Jardim Helena-Vila Mara > Estação São Miguel Paulista' },
  { codigo: 112, descricao: 'Estação Jardim Romano > Estação Engenheiro Manoel Feio' },
  { codigo: 114, descricao: 'Estação Jardim Romano > Estação Itaim Paulista' },
  { codigo: 22, descricao: 'Estação Jardim Silveira > Estação Jardim Belval' },
  { codigo: 54, descricao: 'Estação Jardim Silveira > Estação Jandira' },
  { codigo: 54, descricao: 'Estação Jandira > Estação Jardim Silveira' },
  { codigo: 55, descricao: 'Estação Jandira > Estação Sagrado Coração' },
  { codigo: 10, descricao: 'Estação Jaraguá > Estação Perus' },
  { codigo: 9, descricao: 'Estação Jaraguá > Estação Vila Clarice' },
  { codigo: 60, descricao: 'Estação José Bonifácio > Estação Dom Bosco' },
  { codigo: 61, descricao: 'Estação José Bonifácio > Estação Guaianases' },
  { codigo: 2, descricao: 'Estação Jundiaí > Estação Várzea Paulista' },
  { codigo: 87, descricao: 'Estação Jurubatuba > Estação Autódromo' },
  { codigo: 86, descricao: 'Estação Jurubatuba > Estação Socorro' },
  { codigo: 25, descricao: 'Estação Lapa (L7) > Estação Água Branca' },
  { codigo: 26, descricao: 'Estação Lapa (L7) > Estação Pirituba' },
  { codigo: 4, descricao: 'Estação Lapa (L8) > Estação Domingos de Moraes' },
  { codigo: 5, descricao: 'Estação Lapa (L8) > Estação Palmeiras - Barra Funda' },
  { codigo: 41, descricao: 'Estação Luz (L7) > Estação Água Branca' },
  { codigo: 1, descricao: 'Estação Luz (L7) > Estação Brás' },
  { codigo: 63, descricao: 'Estação Manoel Feio > Estação Aracaré' },
  { codigo: 111, descricao: 'Estação Manoel Feio > Estação Itaquaquecetuba' },
  { codigo: 18, descricao: 'Estação Mauá > Estação Guapituba' },
  { codigo: 17, descricao: 'Estação Mauá > Estação Capuava' },
  { codigo: 22, descricao: 'Estação Mogi das Cruzes > Estação Estudantes' },
  { codigo: 21, descricao: 'Estação Mogi das Cruzes > Estação Braz Cubas' },
  { codigo: 117, descricao: 'Estação Morumbi > Estação Berrini' },
  { codigo: 34, descricao: 'Estação Morumbi > Estação Granja Julieta' },
  { codigo: 3, descricao: 'Estação Osasco > Estação Carapicuíba' },
  { codigo: 3, descricao: 'Estação Osasco > Estação Comandante Sampaio' },
  { codigo: 104, descricao: 'Estação Palmeiras - Barra Funda > Estação Água Branca' },
  { codigo: 5, descricao: 'Estação Palmeiras - Barra Funda > Estação Lapa (L8)' },
  { codigo: 41, descricao: 'Estação Palmeiras - Barra Funda > Estação Luz (L7)' },
  { codigo: 11, descricao: 'Estação Perus > Estação Caieiras' },
  { codigo: 10, descricao: 'Estação Perus > Estação Jaraguá' },
  { codigo: 31, descricao: 'Estação Pinheiros > Estação Cidade Universitária' },
  { codigo: 32, descricao: 'Estação Pinheiros > Estação Hebraica-Rebouças' },
  { codigo: 26, descricao: 'Estação Pirituba > Estação Lapa (L7)' },
  { codigo: 43, descricao: 'Estação Pirituba > Estação Vila Clarice' },
  { codigo: 31, descricao: 'Estação Poá > Estação Calmon Viana' },
  { codigo: 62, descricao: 'Estação Poá > Estação Ferraz de Vasconcelos' },
  { codigo: 1, descricao: 'Estação Prefeito Saladino > Estação Brás' },
  { codigo: 4, descricao: 'Estação Prefeito Saladino > Estação Santo André' },
  { codigo: 52, descricao: 'Estação Quitaúna > Estação Comandante Sampaio' },
  { codigo: 53, descricao: 'Estação Quitaúna > Estação General Miguel Costa' },
  { codigo: 13, descricao: 'Estação Rio Grande da Serra > Estação Ribeirão Pires' },
  { codigo: 14, descricao: 'Estação Ribeirão Pires > Estação Guapituba' },
  { codigo: 13, descricao: 'Estação Ribeirão Pires > Estação Rio Grande da Serra' },
  { codigo: 55, descricao: 'Estação Sagrado Coração > Estação Jandira' },
  { codigo: 23, descricao: 'Estação Sagrado Coração > Estação Itapevi' },
  { codigo: 4, descricao: 'Estação Santo André > Estação Prefeito Saladino' },
  { codigo: 16, descricao: 'Estação Santo André > Estação Capuava' },
  { codigo: 35, descricao: 'Estação Santo Amaro > Estação Granja Julieta' },
  { codigo: 36, descricao: 'Estação Santo Amaro > Estação Socorro' },
  { codigo: 2, descricao: 'Estação São Caetano > Estação Tamanduateí' },
  { codigo: 3, descricao: 'Estação São Caetano > Estação Utinga' },
  { codigo: 122, descricao: 'Estação São Miguel Paulista > Estação Engenheiro Goulart' },
  { codigo: 113, descricao: 'Estação São Miguel Paulista > Estação Jardim Helena-Vila Mara' },
  { codigo: 36, descricao: 'Estação Socorro > Estação Santo Amaro' },
  { codigo: 86, descricao: 'Estação Socorro > Estação Jurubatuba' },
  { codigo: 40, descricao: 'Estação Suzano > Estação Calmon Viana' },
  { codigo: 39, descricao: 'Estação Suzano > Estação Jundiapeba' },
  { codigo: 5, descricao: 'Estação Tamanduateí > Estação Ipiranga' },
  { codigo: 2, descricao: 'Estação Tamanduateí > Estação São Caetano' },
  { codigo: 72, descricao: 'Estação Tatuapé > Estação Corinthians-Itaquera' },
  { codigo: 105, descricao: 'Estação Tatuapé > Estação Brás' },
  { codigo: 119, descricao: 'Estação Tatuapé > Estação Engenheiro Goulart' },
  { codigo: 118, descricao: 'Estação USP Leste > Estação Engenheiro Goulart' },
  { codigo: 119, descricao: 'Estação USP Leste > Estação Comendador Ermelino' },
  { codigo: 3, descricao: 'Estação Utinga > Estação Santo André' },
  { codigo: 3, descricao: 'Estação Utinga > Estação São Caetano' },
  { codigo: 9, descricao: 'Estação Vila Clarice > Estação Jaraguá' },
  { codigo: 43, descricao: 'Estação Vila Clarice > Estação Pirituba' },
  { codigo: 33, descricao: 'Estação Vila Olímpia > Estação Berrini' },
  { codigo: 32, descricao: 'Estação Vila Olímpia > Estação Cidade Jardim' },
  { codigo: 217, descricao: 'Estação Vila Aurora > Estação Jaraguá' },
  { codigo: 11, descricao: 'Estação Vila Aurora > Estação Perus' },
  { codigo: 116, descricao: 'Estação Vila Aurora > Estação Pirituba' },
  { codigo: 121, descricao: 'Estação Vila Aurora > Estação Suzano' },
  { codigo: 125, descricao: 'Final de Linha > Estação Aeroporto-Guarulhos' },
  { codigo: 126, descricao: 'Final de Linha > Estação Paranapiacaba' },
  { codigo: 997, descricao: 'Não se aplica(m)' },
  { codigo: 998, descricao: 'Inexistente(s)' },
  { codigo: 999, descricao: 'Indefinido(a)(s)' },
  { codigo: 1000, descricao: 'Não avaliado(a)(s)' }
];