export const VIA_CPTM = [
  { codigo: 1, descricao: 'Via 01' },
  { codigo: 2, descricao: 'Via 02' },
  { codigo: 3, descricao: 'Via 03' },
  { codigo: 4, descricao: 'Via 04' },
  { codigo: 5, descricao: 'Via 05' },
  { codigo: 6, descricao: 'Via 06' },
  { codigo: 7, descricao: 'Via 08' },
  { codigo: 8, descricao: 'Via 09' },
  { codigo: 9, descricao: 'Via 10' },
  { codigo: 10, descricao: 'Via 01S - Trecho 1' },
  { codigo: 11, descricao: 'Via 01S - Trecho 2' },
  { codigo: 12, descricao: 'Via 02S - Trecho 1' },
  { codigo: 13, descricao: 'Via 02S - Trecho 2' },
  { codigo: 14, descricao: 'Via 03S - Trecho 2' },
  { codigo: 15, descricao: 'Via 03E - Trecho 2' },
  { codigo: 16, descricao: 'Via 04E - Trecho 2' },
  { codigo: 17, descricao: 'Via Auxiliar' },
  { codigo: 18, descricao: 'Via Variante' },
  { codigo: 19, descricao: 'Travessão - AMV' },
  { codigo: 97, descricao: 'Não se aplica(m)' },
  { codigo: 98, descricao: 'Inexistente(s)' },
  { codigo: 99, descricao: 'Indefinido(a)(s)' },
  { codigo: 100, descricao: 'Não avaliado(a)(s)' }
];